spring.datasource.url=jdbc:h2:mem:catalog;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=target/schema-catalog.sql

eureka.client.enabled=false
spring.cloud.config.enabled=false
spring.cloud.discovery.enabled=false

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.cors.allowed-origins=http://localhost:3001
